<?php 
	$id = "em_ajax_products_".md5(uniqid(rand())).md5($block->getData('data'));	 		
?>
<div id="<?php echo $id ?>" class="emtabs-ajaxblock-loading ajaxblock"></div>
<script type="text/javascript">    
require(['jquery','emslider'],function($){
var divContent = $('#<?php echo $id ?>').closest(".tab-content").first();
    if(divContent.length){            	
        $('a[href="#' + divContent.attr("id") + '"]').click(function(event){
            event.preventDefault();
            var $_this = $(this);            
			var $_id = $_this.parent().parent('.custom-tab').attr('id');
			if (typeof $_id !== typeof undefined && $_id !== false) {
				var $_currentTittle = $("[data-emajaxtabs-title='#"+$_id+"']");
				var $_listTitle = $('#'+$_id);
				$_currentTittle.empty().html($_this.html());
				if($_listTitle.hasClass('active')){
					$_listTitle.removeClass('active').addClass('hidden-xs');
				}
				if($_currentTittle.hasClass('active')){
					$_currentTittle.removeClass('active');
				}
			}            
                 
            $_this.parent().addClass("active");
            $_this.parent().siblings().removeClass("active");
            var tab = $($_this.attr("href"));	     
            tab.siblings().css("display", "none");
            tab.siblings().removeClass("active");
            tab.addClass("active");
            tab.fadeIn("fast");
    	});	
    	
    	var tabContent = $('#<?php echo $id ?>').parents(".tab-content").first();		
    	if(tabContent.length > 0){	
    		var elTitle = $('.custom-tab').find("a[data-tab='" + tabContent.attr("id") + "']").first();				
    		if(elTitle.parent("li").hasClass("active")){
    			$(elTitle.attr("href")).addClass("active");
                
                var $_request_<?php echo $id ?> = $.ajax({
                    url: '<?php echo ($block->getRequest()->isSecure()) ? $block->getUrl("ajaxblock",array('_secure'=>true)) : $block->getUrl("ajaxblock") ?>',
                    method: 'POST',
                    data: {data: '<?php echo $block->getData('data') ?>'},
                });
                $_request_<?php echo $id ?>.done(function(data){
                    var $_e = $('#<?php echo $id ?>');
                    $_e.html(data).trigger("contentUpdated");   
                    $_e.removeClass('emtabs-ajaxblock-loading').addClass('emtabs-ajaxblock-loaded');                   
                });                	 
    		}else{    		  
    			tabContent.hide();
    			elTitle.bind("click",function (e) {
    			     e.preventDefault();
    			     var $_this = $(this);
                     		var $_id = $_this.parent().parent('.custom-tab').attr('id');
					if (typeof $_id !== typeof undefined && $_id !== false) {
						var $_currentTittle = $("[data-emajaxtabs-title='#"+$_id+"']");
						 var $_listTitle = $('#'+$_id);
						 $_currentTittle.empty().html($_this.html());
						 if($_listTitle.hasClass('active')){
							$_listTitle.removeClass('active').addClass('hidden-xs');
						 }
						 if($_currentTittle.hasClass('active')){
							$_currentTittle.removeClass('active');
						 }
					}                   
    			     
    				if(!$_this.hasClass("loaded")){	
    				    var that = this;                        
                        var $_request_<?php echo $id ?> = $.ajax({
			    			url: '<?php echo ($block->getRequest()->isSecure()) ? $block->getUrl("ajaxblock",array('_secure'=>true)) : $block->getUrl("ajaxblock") ?>',
                            method: 'POST',
                            data: {data: '<?php echo $block->getData('data') ?>'},
                        });
                        $_request_<?php echo $id ?>.done(function(data){
                            var $_e = $('#<?php echo $id ?>');
                            $_e.html(data).trigger("contentUpdated");   
                            $(that).addClass("loaded");
                            $_e.removeClass('emtabs-ajaxblock-loading').addClass('emtabs-ajaxblock-loaded');                                                                                                        
                        });
    	            }
    			});
                
    		}
    
    	}
    }else{
	var $_request_<?php echo md5($block->getData('data')) ?> = $.ajax({
		url: '<?php echo ($block->getRequest()->isSecure()) ? $block->getUrl("ajaxblock",array("_secure"=>true)) : $block->getUrl("ajaxblock") ?>',
		method : 'POST',
		data: {data: '<?php echo $block->getData("data") ?>'},
	});    
	$_request_<?php echo md5($block->getData('data')) ?>.done(function(data){
		var $_e = $('#<?php echo $id ?>');
		$_e.html(data);
		$_e.removeClass('emtabs-ajaxblock-loading').addClass('emtabs-ajaxblock-loaded');     
		$('#<?php echo $id ?>').trigger("contentUpdated");
	});
    	
    }
});    
</script>
