<?php
$_product = $this->getProduct();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productModel = $_objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
$_images = $_productModel->getMediaGalleryImages();
$_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$width = $this->getImageWidth();
$height = $this->getImageHeight();
$_id = uniqid('more-view-');
?>

<?php if(count($_images)): ?>
<div class="more-view-items" id="<?php echo $_id ?>" style="width:100%;">
<?php foreach($_images as $_image): ?>
	<?php
	    $thumbUrl = $_imageHelper->init($_product,'category_page_grid')->setImageFile($_image->getFile())->resize(200,200)->getUrl();
		$fullUrl = $_imageHelper->init($_product,'category_page_grid')->setImageFile($_image->getFile())->resize($width,$height)->getUrl();
	?>
	<div class="more-view-item">
    	<a href="<?php echo $fullUrl ?>" class="more-view-img">
    		<img src="<?php echo $thumbUrl ?>" class="img-responsive" />
        </a>
    </div>
<?php endforeach ?>
</div>
<script type="text/javascript">
require(['jquery'],function($){
	var $wrap = $('#<?php echo $_id ?>');
	$('.more-view-img',$wrap).on('click',function(e){
		e.preventDefault();
		var $mainImg = $wrap.parents('.product-item-info').first().find('img.em-alt-hover').first();
		var src = $(this).attr('href');
		$mainImg.attr('src',src);
	});
});
</script>
<?php endif ?>
