<?php  
/**
 * @extension   Remmote_Facebookpixelremarketing
 * @author      Remmote    
 * @copyright   2017 - Remmote.com
 * @descripion  Pixel code template
 */
?>
<!-- Facebook Pixel Code - Remmote © -->
<script> 
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? 
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; 
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; 
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, 
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init',  '<?php echo $block->getPixelId() ?>');
fbq('track', 'PageView');

<?php
//Stardand events
echo $block->getViewContentEvent();
echo $block->getSearchEvent();
echo $block->getAddToCartEvent();
echo $block->getAddToWishlistEvent();
echo $block->getInitiateCheckoutEvent();
echo $block->getAddPaymentInfoEvent();
echo $block->getPurchaseEvent();
echo $block->getLeadEvent();
echo $block->getCompleteRegistrationEvent();
?>
</script> 
<noscript><img height="1" width="1" style="display:none" alt="Facebook Pixel" src="https://www.facebook.com/tr?id=<?php echo $block->getPixelId() ?>&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code - Remmote © -->