<div id="loader-wrapper">
    <img class="logo_loader" src="<?php echo $block->getViewFileUrl('images/em_logo_loading.png'); ?>" alt="" />
    <div id="loader"></div> 
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<script type="text/javascript">
	require(['jquery','domReady!'],function($){
		setTimeout(function(){
		      $_body = jQuery('body');
		  	$_body.addClass('loaded');
		  }, 1000);   	
	});
</script>
