<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Emthemes\FilterProduct\Block\Product\ProductsList
 */
?>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_sliderItem = $block->getData('slider_item') ? $block->getData('slider_item') : 4;
$_productSize = $_productCollection->count();
if($_helper->isModuleOutputEnabled('Emthemes_ProductLabels'))
	$_labelHelper =  $this->helper('Emthemes\ProductLabels\Helper\Data');
?>

<?php if (!$_productSize): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $_quickShopHelper =  $this->helper('Emthemes\QuickShop\Helper\Data');
    $type = 'widget-product-list';
    $viewMode = 'grid';
    $image = 'category_page_grid';    
    $title = $block->getTitle() ? __($block->getTitle()) : '';
	$uniqId = uniqid('product_block_');
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $alt_img = true;
    $_columnCount = $this->getData('columns_count')?$this->getData('columns_count'):1;
?>
    <div class="em-grid-03 block widget block-products-grid list" id="<?php echo $uniqId ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><span><?php /* @escapeNotVerified */ echo $title; ?></span></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="product wrapper products-row">
		    <?php $iterator = 0; foreach ($_productCollection as $_product): ?>
              	<?php if ($_columnCount > 0 && $iterator%$_columnCount==0 || $_columnCount <= 0 && $iterator == 0): ?>
				<div class="product-items products-grid">
                <?php endif; ?>
                    <div class="product-item">
                        <div class="product-item-info" data-container="product-grid">
							<div class="product-shop-top">
							<?php if($_helper->isModuleOutputEnabled('Emthemes_ProductLabels')): ?>
								<?php $_labelHelper->display($_product) ?>
							<?php endif; ?>
								<?php
					            $productImage = $block->getImage($_product, $image);
					            if ($pos != null) {
					                $position = ' style="left:' . $productImage->getWidth() . 'px;'
					                    . 'top:' . $productImage->getHeight() . 'px;"';
					            }
					            ?>
					            <?php 
                      	if($productImage->getWidth() && $productImage->getHeight())
								          $_ratio =  $productImage->getHeight() / $productImage->getWidth(); 
                        else
                          $_ratio =  1; 
	         						?>
					            <?php // Product Image ?>
					            <?php if($block->isShow('thumb')): ?>
					            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
					                  <?php if ($alt_img): ?>                                         
                              <?php 
                                    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                    $productAltImage = $_imagehelper->init($_product, 'category_page_grid_thumbnail')->resize($productImage->getWidth(),$productImage->getHeight()); 
                              ?>                           
                                  <span class="product-image-container em-alt-hover"
                                    style="width:<?php /* @escapeNotVerified */ echo $productImage->getWidth() ?>px;">
                                  <span class="product-image-wrapper"
                                   style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;">                 
                                          <img class="em-alt-hover img-responsive " src="<?php echo $productAltImage->getUrl()?>"                                          
                                          width="<?php echo $productImage->getWidth(); ?>" height="<?php echo $productImage->getHeight() ;?>" 
                                          alt="<?php echo $block->stripTags($productAltImage->getLabel(), null, true) ?>" />
                                           </span></span>
          					    <?php endif ?>
					                <?php //echo $productImage->toHtml();
                                                $product_img = $_imagehelper->init($_product, $image)->resize($productImage->getWidth(),$productImage->getHeight()); 
                                               ?>
                                              <span class="product-image-container <?php echo ($alt_img) ? 'em-alt-org' : '' ?>"
                                                style="width:<?php /* @escapeNotVerified */ echo $productImage->getWidth(); ?>px;">
                                              <span class="product-image-wrapper"
                                                    style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;">
                                                  <img class="product-image-photo"
                                                       src="<?php /* @escapeNotVerified */ echo $product_img->getUrl(); ?>"
                                                       width="<?php echo $productImage->getWidth(); ?>" height="<?php echo $productImage->getHeight() ;?>" 
                                                       alt="<?php /* @escapeNotVerified */ echo $block->stripTags($product_img->getLabel(), null, true); ?>" /></span>
                                          </span>
					            </a>
					            <?php endif ?>

								<div class="bottom">
                                	<?php if($block->isShow('addto')): ?>                                                
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; // end wishlist ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToComparePostParams($_product);?>'
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; // end compare ?>          												
                                        </div>	
                                    <?php endif; //end add to ?>
									<?php if($_quickShopHelper->getConfig('quickshop/general/active')): ?>
                                    <div class="quickshop-link-container hidden-xs">
                                       <?php echo $_quickShopHelper->getQuickShopButton($_product); ?>
                                    </div>
                                    <?php endif; ?>
                                </div>
                      
	                        </div>		
						
                        
                    
                <div class="product-item-details">
								<?php // show name ?>
								<?php if($block->isShow('name')): ?>
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_product->getName()) ?>
                                    </a>
                                </strong>
                                <?php endif; ?>
                                <?php //show sku ?>
                                <?php if($block->isShow('sku')): ?>
									               <p class="sku"><?php echo $_product->getSku(); ?></p>
                                <?php endif; ?>
                                
                                <?php // show short description ?>
                              <?php if($block->isShow('description')): ?>
                                   <?php $desc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                               
                                   <?php if($desc): ?>
                                        <div class="product-item-description">
                                        <?php
									        if(strlen($desc)>80) {
									                $strCutTitle = substr($desc, 0, 80);
									                $desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
									        }
			                			?>
                                        <?php /* @escapeNotVerified */ echo  $desc; ?>
                                            <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>"
                                               class="action more"><?php /* @escapeNotVerified */ echo __('...') ?></a>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>                                                                                            
                                <?php // show price ?>
                                <?php if($block->isShow('price')): ?>
				                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
			                	<?php endif ?>
								        <?php // show review ?>
                                <?php if($block->isShow('review')): ?>
				                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
			                	<?php endif ?>			
                                <div class="em-element-display-hover bottom">                	
                                    <div class="em-btn-addto">
                                        <div class="product-item-actions  product-item-actions <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>">
                                        <?php if($block->isShow('addtocart')): ?>
                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                  <?php if ($_product->isSaleable()): ?>
                                                      <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                      <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post" <?php if (!$block->isRedirectToCartEnabled()) : ?>data-mage-init='{"catalogAddToCart": {}}'<?php endif ?>>
                                                          <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                          <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                          <?php echo $block->getBlockHtml('formkey')?>
                                                          <button type="submit"
                                                                  title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                  class="action tocart primary">
                                                              <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                          </button>
                                                      </form>
                                                  <?php else: ?>
                                                      <?php if ($_product->getIsSalable()): ?>
                                                          <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                      <?php else: ?>
                                                          <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                      <?php endif; ?>
                                                  <?php endif; //end isSealable?>
                                              </div>
                                          <?php endif; // end cart button ?>								
                                        </div>												 
                                    </div>		
                                </div>				
			                	<?php echo $block->getProductDetailsHtml($_product); ?>                                 
                            </div>   
                       </div>                     
                    </div>
            <?php if ( $_columnCount > 0 && ($iterator+1)%$_columnCount==0 || $iterator+1==$_productSize ): ?>
	             </div>
	        <?php endif; ?>
            <?php $iterator++; ?>
            <?php endforeach ?>
                </div>
            <?php echo $block->getToolbarHtml() ?>
        </div>
    </div>  
<?php if($block->getData('show_slider')): ?>
<script type="text/javascript">
    require(['jquery','emslider'],function($){
            var owl = $('#<?php echo $uniqId ?> .products-row');
            if(owl.length && !owl.hasClass("owl-loaded")){   
                owl.addClass("owl-carousel"); 
                owl.owlCarousel({
                  responsiveClass:true,
                  items: <?php echo $_sliderItem ?>,
                      responsive:{
                          0:{items: 1,},
						  320: {items: 2},
                          480:{items: 2},
                          768:{items:<?php echo ($_sliderItem > 2) ? $_sliderItem - 1 : $_sliderItem ?>,},
                          1024:{items:<?php echo $_sliderItem ?>,}
                      },
					  margin:-1,
                      nav: true,
                      dots: false,
                      rtl: (EM.SETTING.RTL == 1) ? true : false,
                });         
            }     

        });
</script>
<?php endif ?>
<script type="text/javascript">
    require(['jquery','equalElement', 'domReady!'],function($){
		var $wrap = $('#<?php echo $uniqId ?>');
		if($wrap.parents('.em-tabs').length > 0){
			$wrap = $wrap.parents('.em-tabs').first();
		}
		var makeEqualElement = function(){
			$wrap.equalElement({
				target: '.product-item-details'       
			});
		}
		var timeout = setTimeout(makeEqualElement,500);
		$(window).resize(function(){
			if(timeout) clearTimeout(timeout);
			timeout = setTimeout(function(){
				makeEqualElement();
			},500);
		});
	});
</script>
<?php endif;?>