<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Emthemes\FilterProduct\Block\Product\ProductsList
 */
?>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_productSize = $_productCollection->count();
if($_helper->isModuleOutputEnabled('Emthemes_ProductLabels'))
	$_labelHelper =  $this->helper('Emthemes\ProductLabels\Helper\Data');
$_filterProductHelper =  $this->helper('Emthemes\FilterProduct\Helper\Data');
?>

<?php if (!$_productSize): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $_quickShopHelper =  $this->helper('Emthemes\QuickShop\Helper\Data');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $viewMode = 'grid';
    $image = 'category_page_grid';    
    $title = $block->getTitle() ? __($block->getTitle()) : '';

    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $alt_img = true;
?>
    <div class="em-grid-03 block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content <?php echo $classid ?>">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="product wrapper products-<?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <ol class="product-items products list items <?php /* @escapeNotVerified */ echo $type; ?>" style="width:100%">
                    <?php $iterator = 1; ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li style="width:100%" class="product-item">' : '</li><li style="width:100%" class="product-item">' ?>
                        <div class="product-item-info row" data-container="product-grid">
							<div class="product-shop-top col-sm-12">
							<?php if($_helper->isModuleOutputEnabled('Emthemes_ProductLabels')): ?>
                            <?php $_labelHelper->display($_product) ?>
                            <?php endif; ?>	
                            <?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
							  $position = ' style="left:' . $productImage->getWidth() . 'px;'
								  . 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php 
							if($productImage->getWidth() && $productImage->getHeight())
								$_ratio =  $productImage->getHeight() / $productImage->getWidth(); 
							else
								$_ratio =  1; 
							?>
                            <?php // Product Image ?>
                            <?php if($block->isShow('thumb')): ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php if ($alt_img): ?> 
                                
                                  <?php 
                                        $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                        $productAltImage = $_imagehelper->init($_product, 'category_page_grid_thumbnail')->resize($productImage->getWidth(),$productImage->getHeight()); 
                                  ?>                           
                              <span class="product-image-container em-alt-hover"
                            style="width:100%">
                                <span class="product-image-wrapper"
                                 style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;">               
                                        <img class="em-alt-hover img-responsive " src="<?php echo $productAltImage->getUrl()?>" 
                                        alt="<?php echo $block->stripTags($productAltImage->getLabel(), null, true) ?>" />
                                </span>
                              </span>
        					          <?php endif ?>  
							<?php //echo $productImage->toHtml();
	                            $product_img = $_imagehelper->init($_product, $image)->resize($productImage->getWidth(),$productImage->getHeight()); 
                            ?>
                            <span class="product-image-container <?php echo ($alt_img) ? 'em-alt-org' : '' ?>"
                              style="width:100%">
                              <span class="product-image-wrapper"
                                   style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;">
                                <img class="product-image-photo"
                                     src="<?php /* @escapeNotVerified */ echo $product_img->getUrl(); ?>"
                                     width="<?php echo $productImage->getWidth(); ?>" height="<?php echo $productImage->getHeight() ;?>" 
                                     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($product_img->getLabel(), null, true); ?>" />
                              </span>
                             </span>
                            </a>
                          <?php endif ?>
                          <div class="quickshop-link-container hidden-xs">
    				  <?php if($_quickShopHelper->getConfig('quickshop/general/active')): ?>
                          	<?php echo $_quickShopHelper->getQuickShopButton($_product); ?>
                          <?php endif; ?> 				
                          </div>
                          <!-- More View -->
                          <?php
							 echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setProduct($_product)->setImageWidth($productImage->getWidth())->setImageHeight($productImage->getHeight())->setTemplate('Emthemes_FilterProduct::detail/moreview.phtml')->toHtml();
						  ?>
                          <!-- End More View -->
                      </div>
                      <div class="product-item-details col-sm-12">
                      	<?php if($_filterProductHelper->getPriceCountDown($_product)) : ?>                                    
                                    <div id="countdowntimer" class="countdowntimer"><span id="<?php echo $_product->getId() ?>"><span></div>
                                    <script type="text/javascript">
                                      require([
                                        'jquery',                                        
                                        'countdownTimer'
                                      ], function ($) {                                      
                                                                                
                                        $("#<?php echo $_product->getId()?>").countdowntimer({
                                          startDate : "<?php echo $_filterProductHelper->getCurrentDate(); ?>",
                                          dateAndTime : "<?php echo str_replace('-','/',$_filterProductHelper->getCountdownEndDate($_product)); ?>",
                                          size : "lg",
                                          regexpMatchFormat: "([1-9][0-9]{0,2}):([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})",
                                          regexpReplaceWith: "<ul><li><span class='day-num'>$1</span><span class='days-txt'>"+"<?php echo __("days") ?>"+"</span> </li><li><span class='hour-num'> $2</span><span class='hour-txt'>"+"<?php echo __("hours") ?>"+"</span> </li><li><span class='minute-num'>$3</span> <span class='minute-txt'>"+"<?php echo __("minutes") ?>"+"</span> </li><li><span class='second-num'>$4</span> <span class='second-txt'>"+"<?php echo __("seconds") ?>"+"</span></li></ul>",
                                          customClass: "clock_1",
											stopButton : "stopBtnhms",
                                          });    
                                      });
                                    </script>
                                    <?php endif; ?>
      								<?php // show name ?>
                        <?php if($block->isShow('name')): ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php endif ?>
                        <?php // show sku ?>
                        <?php if($block->isShow('sku')): ?>
                          <p class="sku"><?php echo $_product->getSku(); ?></p>
                        <?php endif; ?>
                                      
                        <?php // show short description ?>
                        <?php if($block->isShow('description')): ?>
                           <?php $desc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                                     
                        <?php if($desc): ?>
                          <div class="product-item-description">
                            <?php
            				        if(strlen($desc)>300) {
            				                $strCutTitle = substr($desc, 0, 300);
            				                $desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
            				        }
      			                 ?>
                            <?php /* @escapeNotVerified */ echo  $desc; ?>
                            <a title="<?php echo $block->escapeHtml($_product->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" class="action more"><?php /* @escapeNotVerified */ echo __('...') ?></a>
                          </div>
                          <?php endif; ?>
                        <?php endif; ?>
                                      
                                      
                        <?php // show price ?>
                        <?php if($block->isShow('price')): ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php endif ?>
                         <?php echo $block->getProductDetailsHtml($_product); ?>
                        
                         <?php if($block->isShow('review')): ?>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php endif ?>
                        <div class="em-element-display-hover bottom">
                            <div class="em-btn-addto">
                              <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>                    
                                <?php if($block->isShow('addtocart')): ?>
                                  <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                      <?php if ($_product->isSaleable()): ?>
                                          <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                          <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post" <?php if (!$block->isRedirectToCartEnabled()) : ?>data-mage-init='{"catalogAddToCart": {}}'<?php endif ?>>
                                              <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                              <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                              <?php echo $block->getBlockHtml('formkey')?>
                                              <button type="submit"
                                                      title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                      class="action tocart primary">
                                                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                              </button>
                                          </form>
                                      <?php else: ?>
                                          <?php if ($_product->getIsSalable()): ?>
                                              <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                          <?php else: ?>
                                              <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                          <?php endif; ?>
                                      <?php endif; ?>
                                  </div>
                              <?php endif ?>
                              <?php if($block->isShow('addto')): ?>
                              <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                  <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                      <a href="#"
                                         class="action towishlist"
                                         title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                         aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                         data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                         data-action="add-to-wishlist"
                                         role="button">
                                          <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                      </a>
                                  <?php endif; ?>
                                  <?php
                                  $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                  ?>
                                  <a href="#"
                                     class="action tocompare"
                                     title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                     aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                     data-post='<?php /* @escapeNotVerified */ echo $block->getAddToComparePostParams($_product); ?>'
                                     role="button">
                                      <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                  </a>
                              </div>
                              <?php endif ?>                             
                            </div>
                          </div>
                        </div>                                    
                      </div>
                    </div>
                  <?php echo($iterator == $_productSize+1) ? '</li>' : '' ?>
                <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getToolbarHtml() ?>
        </div>
    </div>   

<?php if($block->getData('show_slider')): ?>
<script type="text/javascript">
    require(['jquery','emslider'],function($){
            var owl = $('.<?php echo $classid ?> .product-items');
            if(owl.length){   
                owl.addClass("owl-carousel"); 
                owl.owlCarousel({
					pullDrag: false,
				  	freeDrag: false,
                  	responsiveClass: true,
					responsive:{
                          0:{
                              items:1,
                          },
                          480:{
                              items:1,
                          },
                          768:{
                              items:1,                              
                          },
                          1024:{
                              items:1,
                          }
                      },
					  margin:0,
                      nav: true,
                      dots: false,
                      rtl: (EM.SETTING.RTL == 1) ? true : false,
                });         
            }
			
			var media = $('.<?php echo $classid ?> .more-view-items');
			if(media.length && !media.hasClass("owl-loaded")){   
				media.addClass("owl-carousel"); 
					media.owlCarousel({
					  responsiveClass:true,
					  items: 3,
					  responsive:{
						  0:{
							  items: 2,
						  },
						  480:{
							  items: 3,
						  },
						  768:{
							  items: 2,                              
						  },
						  1024:{
							  items: 3,
						  }
					  },
					  margin:-1,
					  nav: true,
					  dots: false,
					  rtl: (EM.SETTING.RTL == 1) ? true : false,
					});
			}
			setTimeout(function(){
				$(window).trigger('resize');
			},500);
            
        });
</script>
<?php endif ?>
<?php endif;?>
