<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<?php $settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); ?>
<?php if($settingHelper->getConfig('general_section/general_blocks/handle_login_form') == 1): ?>
<div class="block block-customer-login" style="display:none">   
	<div class="block-content" aria-labelledby="block-customer-login-heading">
    	<ul class="list-inline header-list-link">
            <li class="myaccount-link">
                <a title="<?php echo $block->escapeHtml(__('My Account')); ?>" class="link-account" href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl().'customer/account'; ?>">
                    <?php echo $block->escapeHtml(__('My Account')); ?>
                </a>
            </li>
            <li class="myorder-link">
                <a title="<?php echo $block->escapeHtml(__('My Account')); ?>" class="link-account" href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl().'sales/order/history/'; ?>">
                    <?php echo $block->escapeHtml(__('My Order')); ?>
                </a>
            </li>
	    	<?php echo $block->getChildHtml() ?>
            <li class="contact-link">
                <a title="<?php echo $block->escapeHtml(__('My Account')); ?>" class="link-account" href="<?php /* @escapeNotVerified */ echo $block->getBaseUrl().'contact/'; ?>">
                    <?php echo $block->escapeHtml(__('Contact Us')); ?>
                </a>
            </li>
        </ul>
    </div>
</div>
<script type="text/javascript">
	require(['jquery','dropdownDialog','domReady!'],function($){
		function effectLoginForm() {
			var sLogin = $('.header-account .block-customer-login');
			var sLink = $('.link-account');
			var sDivLink = $('.header-account');
			 <?php if( $settingHelper->checkMobile()=='false'): ?>
			  var tmlink = false;	       
			  function showlink(el) {
				  if(tmlink) clearTimeout(tmlink);
				  tmlink = setTimeout(function() {
					  el.stop().slideDown();
				  }, 200);
			  }    
			  function hidelink(el) {
				  clearTimeout(tmlink);
				  tmlink = setTimeout(function() {
					  el.stop().slideUp();
				  }, 200);
			  }
			  sDivLink.mouseover(function(){
				  showlink(sLogin);
			  });
			  sDivLink.mouseout(function(){
				  hidelink(sLogin);
			  });
			  <?php endif; ?>
		}
		effectLoginForm();
	});
</script>
<?php endif; ?>