<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_limit = $this->getData('limit')?$this->getData('limit'):3;
	$columnsCount = $this->getData('columns_count')?$this->getData('columns_count'):3;
	$_postCollection = $block->getPostCollection()->setPageSize($_limit);
	$_helper = $this->helper('Magefan\Blog\Helper\Image');
	$_width = 580;
	$_height = 319;
	$classid = md5(json_encode($block->getPostCollection()));
	$viewMode = $this->getData('view_mode')?$this->getData('view_mode'):0;
	if($viewMode == 1){
		$col1 = 'bkg-left col-sm-12'; $col2 = 'bkg-right col-sm-12';	
	}else{
		$col1 = 'bkg-top col-sm-24'; $col2 = 'bkg-bottom col-sm-24';
	}
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-static-block">
<div class="em-slider em-slider-navigation-icon em-slider-from-our-blog em-recent-03" id="<?php echo $classid ?>">
	<?php foreach ($_postCollection as $_post) { ?>
	<?php
		$time = strtotime($_post->getData('publish_time'));
		$img = $_helper->init($_post->getImage())->resize(580,319);
	?>
	<div class="em-blog-item em-effect-13 row">
		<div class="em-blog-content <?php echo $col1 ?>">
			<?php if($img): ?>
			<a href="<?php echo $_post->getPostUrl() ?>">
				<img class="img-responsive" src="<?php echo $img ?>" alt="<?php echo $_post->getTitle() ?>">
			</a>
			<?php endif ?>
		</div>
		<div class="em-box <?php echo $col2 ?>">
        	<div class="em-blog-time"><?php echo date('d.m.y',$time)?></div>
			<h4 class="em-blog-title">
			      <a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->short($_post->getTitle(),35) ?></a>
			</h4>
			<div class="em-blog-des">
				<?php echo $block->short($_post->getShortDescription(),150) ?>
			</div>
			<p><a class="link-more" href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read more') ?></a></p>
		</div>
	</div>		
	<?php } ?>
</div>
</div>
<script type="text/javascript">
require([
        'jquery',
        'emslider',
        'domReady!'        
        ],function($){
                if($('#<?php echo $classid ?>').length){
                  $('#<?php echo $classid ?>').addClass('owl-carousel');
                        $('#<?php echo $classid ?>').owlCarousel({
                                loop: false,
                                lazyLoad: true,
                                items: <?php echo $columnsCount ?>,
                                dots: false,
                                nav: true,
                                responsive:{
                                    0:{items:1},
                                  320:{items:2},
                                  640:{items:2},
                                  768:{items:<?php echo $columnsCount ?>},
                                  1024:{items:<?php echo $columnsCount ?>}
                                  }                                
                        });        
                }
        });
</script>

<?php } ?>


