<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
	$_helper = $this->helper('Magefan\Blog\Helper\Image');
	$_width = 580;
	$_height = 319;
        $classid = md5(json_encode($block->getPostCollection()));
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-static-block">
<div class="row">
<div class="em-line-01">
<!--<div class="em-block-title">
	<h2><span><?php echo __('Blog') ?></span></h2>
</div>-->
<div class="em-recent-07" id="<?php echo $classid ?>">
	<?php $i=1;foreach ($_postCollection as $_post) { ?>
	<?php
		$time = strtotime($_post->getData('publish_time'));
		$img = $_helper->init($_post->getImage())->resize(580,319);
	?>	
	    <?php if($i==1): ?>
	    <div class="col-sm-12 em-blog-left">
		<div class="em-blog-item">
		   <?php if($img): ?>
			<a href="<?php echo $_post->getPostUrl() ?>">
				<img class="img-responsive" src="<?php echo $img ?>" alt="<?php echo $_post->getTitle() ?>">
			</a>
		   <?php endif ?>
		    <div class="em-blog-content">
		        <h4 class="em-blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->short($_post->getTitle(),35) ?>
				  </a></h4>
				  <div class="post-by f-left"> 
		            	<?php echo $block->short($_post->getShortDescription(),200) ?>
		            </div>
		        <div class="em-blog-content-bottom">
		            <p class="f-right"><a class="link-more" href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read more') ?></a></p>
		        </div>
		    </div>
		</div>
	    </div>
	    <?php else: ?>
	    <?php if($i==2): ?>
	    <div class="col-sm-12 em-blog-right">
	    <?php endif; ?>
		<div class="row">
		    <div class="col-sm-24">
		        <div class="em-blog-item">
		            <div class="em-blog-content">
		                <h4 class="em-blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->short($_post->getTitle(),35) ?>
				  </a></h4>
		                <p><a class="link-more" href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read more') ?></a></p>
		            </div>
		        </div>
		    </div>
		</div>	
	    <?php if($i==4): ?>		
	    </div>
	    <?php break; ?>
	    <?php endif; ?>
	    <?php endif; ?>
	
	<?php $i++; ?>
	<?php } ?>
</div>
</div>
</div>
</div>
</div>
<?php } ?>
