<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Emthemes\FilterProduct\Block\Product\ProductsList
 */
?>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_productSize = $_productCollection->count();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$serialize = $objectManager->create('\Magento\Framework\Serialize\Serializer\Json');
$_widgetData = base64_encode($serialize->serialize($block->getWidgetData()));
?>
<?php if (!$_productSize): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $_quickShopHelper =  $this->helper('Emthemes\QuickShop\Helper\Data');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $viewMode = 'grid';
    $image = 'category_page_grid';    
    $title = $block->getTitle() ? __($block->getTitle()) : '';

    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;


    $alt_img = true;
    $_columnCount = 1;
    $idJs = $block->getData('unique_id');
    if($_columnCount > 0){
		$infiniteSelector = $idJs . " .widget-products";
		$infiniteItemSelector = $idJs . " .widget-products ul.products-grid";
	} else {
		$infiniteSelector = $idJs . " .widget-products ul.products-grid";
		$infiniteItemSelector = $idJs . " .widget-products ul.products-grid li.item";
	}
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content <?php echo $classid ?>" id="<?php echo $idJs;?>">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="widget-products product wrapper products-<?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">

                    <?php $iterator = 0; ?>
                    <?php foreach ($_productCollection as $_product): ?>
                    <?php if ($_columnCount > 0 && $iterator%$_columnCount==0 || $_columnCount <= 0 && $iterator == 0): ?>
			<ul class="ajax-product products-grid <?php /* @escapeNotVerified */ echo $type; ?>">
				<?php endif ?>
                       <li class="product-item">
                        <div class="product-item-info" data-container="product-grid">
							<div class="product-shop-top">
								<?php
                                    $productImage = $block->getImage($_product, $image);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php 
                                    	if($productImage->getWidth() && $productImage->getHeight())
								$_ratio =  $productImage->getHeight() / $productImage->getWidth(); 
	                                    else
      		                              $_ratio =  1; 
						?>
                                    <?php // Product Image ?>
                                    <?php if($block->isShow('thumb')): ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                          <?php if ($alt_img): ?> 
                                        
                                          <?php 
                                                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                                $productAltImage = $_imagehelper->init($_product, 'category_page_grid_thumbnail')->resize($productImage->getWidth(),$productImage->getHeight()); 
                                          ?>                           
                                         <span class="product-image-container em-alt-hover"
                                    style="width:<?php /* @escapeNotVerified */ echo $productImage->getWidth() ?>px;">
                                  <span class="product-image-wrapper"
						   style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;">                  
                                          <img class="em-alt-hover img-responsive " src="<?php echo $productAltImage->getUrl()?>"                                          
                                          width="<?php echo $productImage->getWidth(); ?>" height="<?php echo $productImage->getHeight() ;?>" 
                                          alt="<?php echo $block->stripTags($productAltImage->getLabel(), null, true) ?>" />
                                           </span></span>
          					    <?php endif ?>
                                        <?php //echo $productImage->toHtml();
                                          $product_img = $_imagehelper->init($_product, $image)->resize($productImage->getWidth(),$productImage->getHeight()); 
                                         ?>
                                        <span class="product-image-container <?php echo ($alt_img) ? 'em-alt-org' : '' ?>"
                                          style="width:<?php /* @escapeNotVerified */ echo $productImage->getWidth(); ?>px;">
                                        <span class="product-image-wrapper"
                                       style="padding-bottom: <?php /* @escapeNotVerified */ echo ($_ratio * 100); ?>%;"> 
                                            <img class="product-image-photo"
                                                 src="<?php /* @escapeNotVerified */ echo $product_img->getUrl(); ?>"
                                                 width="<?php echo $productImage->getWidth(); ?>" height="<?php echo $productImage->getHeight() ;?>" 
                                                 alt="<?php /* @escapeNotVerified */ echo $block->stripTags($product_img->getLabel(), null, true); ?>" /></span>
                                    </span>
                                    </a>
                                    <?php endif ?>
								<div class="em-element-display-hover bottom">
									<div class="em-btn-addto">
										<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>										
											<?php if($block->isShow('addtocart')): ?>
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <?php echo $block->getBlockHtml('formkey')?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif ?>
								<?php if($block->isShow('addto')): ?>
                                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                        <a href="#"
                                                           class="action towishlist"
                                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <a href="#"
                                                       class="action tocompare"
                                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                       role="button">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                </div>
                                            <?php endif ?>
                                            <?php if($_quickShopHelper->getConfig('quickshop/general/active')): ?>
									<?php echo $_quickShopHelper->getQuickShopButton($_product); ?>
								<?php endif; ?> 
										</div>
									</div>
								</div>
                            </div>
                            <div class="product-item-details">
								<?php // show name ?>
                                <?php if($block->isShow('name')): ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                <?php endif ?>
                                <?php // show sku ?>
                                <?php if($block->isShow('sku')): ?>
						<p class="sku"><?php echo $_product->getSku(); ?></p>
                                <?php endif; ?>
                                
                                <?php // show short description ?>
                                <?php if($block->isShow('description')): ?>
                                   <?php $desc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                               
                                   <?php if($desc): ?>
                                            <div class="product-item-description">
                                        <?php
					        if(strlen($desc)>80) {
					                $strCutTitle = substr($desc, 0, 80);
					                $desc = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
					        }
			                ?>
                                                <?php /* @escapeNotVerified */ echo  $desc; ?>
                                                <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                                   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('...') ?></a>
                                            </div>
                                    <?php endif; ?>
                                <?php endif; ?>
                                
                                
                                <?php // show price ?>
                                <?php if($block->isShow('price')): ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php endif ?>
                                 <?php echo $block->getProductDetailsHtml($_product); ?>
                                
                                 <?php if($block->isShow('review')): ?>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                <?php endif ?>

                                
                            </div>
                        </div>
				</li>
				  <?php if ( ($_columnCount > 0 && ($iterator+1)%$_columnCount==0) || $iterator+1==$_productSize): ?>
			</ul>
			<?php endif; ?>
			<?php $iterator++;?>

                    <?php endforeach ?>
            </div>
            <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                    }
                }
                </script>
            <?php endif; ?>
        </div>
    </div>   
	<?php $this->getPagerHtml(); ?>
	<p class="load-more-image" 	<?php echo $block->getData('use_click')== 0 ? "style='display:none'" : "" ?>>
	<a class="load-more" id="<?php echo $idJs;?>-next" href="#"><?php echo __('Show more')?></a>
	</p>
	<script type="text/javascript">
		require(['jquery','infinitescroll','isotope'],function($){
		$('#<?php echo $infiniteSelector;?>').infinitescroll({
			navSelector  	: "#<?php echo $idJs;?>-next:last",
			nextSelector 	: "#<?php echo $idJs;?>-next:last",
			itemSelector 	: "#<?php echo $infiniteItemSelector;?>",
			contentSelector : "#<?php echo $infiniteSelector;?>",
			dataType	 	: 'html',
			loading: {
				img		: "<?php echo $this->getSkinUrl("images/ajax-loader.gif") ?>",
			},
			maxPage		: <?php echo $block->getMaxPage() ?>,
			<?php if($block->getData('use_click')): ?>
			state			: {
				isPaused : true
			},
			<?php endif; ?>
			path			: function(index) {
				return '<?php echo $this->getUrl('filter_product/index')?>?np=' + index + '&params=<?php echo $_widgetData ?>';
			}
		}, function(newElements, data, url){
			<?php if($block->getData('use_click')): ?>
		    	$("#<?php echo $idJs;?>-next:last").show();			
		    	<?php endif; ?>
		    });
		<?php if($block->getData('use_click')): ?>
		$('#<?php echo $idJs;?>-next').click(function(){
			$('#<?php echo $infiniteSelector;?>').infinitescroll('retrieve');
			return false;
		});
		<?php endif; ?>
});
	</script>
<script type="text/javascript">
    require(['jquery','equalElement','domReady!'],function($){
            $('.<?php echo $classid ?> .product-items').equalElement({
                  target: '.product-item-details'                
            });           
        });
</script>
<?php endif;?>
