<?php 
$om = \Magento\Framework\App\ObjectManager::getInstance();
$recaptcha = $om->get('Magecomp\Recaptcha\Block\Recaptcha');
?>
<form class="form password forget mc"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
        <div class="captcha" style="margin:10px 0px">
   			 <div class="g-recaptcha-response" id="g-recaptcha-forgotpassword" data-theme="<?php echo $recaptcha->getThemeOption(); ?>" data-sitekey="<?php echo $recaptcha->getSiteKey(); ?>"> </div>
             <div id="g_recaptcha-error" style="display: none; color: #e02b27; font-size: 1.2rem;" generated="true"><?php /* @escapeNotVerified */ echo __('This is a required field.') ?></div>
    	</div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script type="text/javascript">
var forgotSubmit = false;
function reCaptchaVerify(response) {
	if (response) {
        forgotSubmit = true;
    }
}
document.forms['form-validate'].addEventListener('submit',function(e){
    if (!forgotSubmit) {
        jQuery('#g_recaptcha-error').show();
		e.preventDefault();
	}
})
</script>

